/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    files: File;
    cohorts: Cohort;
    enrollments: Enrollment;
    invites: Invite;
    contracts: Contract;
    modules: Module;
    'training-sessions': TrainingSession;
    'module-notes': ModuleNote;
    scores: Score;
    'logbook-entries': LogbookEntry;
    evaluations: Evaluation;
    workplans: Workplan;
    documents: Document;
    'media-assets': MediaAsset;
    'alumni-profiles': AlumniProfile;
    announcements: Announcement;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    files: FilesSelect<false> | FilesSelect<true>;
    cohorts: CohortsSelect<false> | CohortsSelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    invites: InvitesSelect<false> | InvitesSelect<true>;
    contracts: ContractsSelect<false> | ContractsSelect<true>;
    modules: ModulesSelect<false> | ModulesSelect<true>;
    'training-sessions': TrainingSessionsSelect<false> | TrainingSessionsSelect<true>;
    'module-notes': ModuleNotesSelect<false> | ModuleNotesSelect<true>;
    scores: ScoresSelect<false> | ScoresSelect<true>;
    'logbook-entries': LogbookEntriesSelect<false> | LogbookEntriesSelect<true>;
    evaluations: EvaluationsSelect<false> | EvaluationsSelect<true>;
    workplans: WorkplansSelect<false> | WorkplansSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'media-assets': MediaAssetsSelect<false> | MediaAssetsSelect<true>;
    'alumni-profiles': AlumniProfilesSelect<false> | AlumniProfilesSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      sendSessionReminder: TaskSendSessionReminder;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'trainer' | 'intern' | 'supervisor';
  /**
   * "pending" is set automatically for §6.2 self-registrations, awaiting admin review (target 24h turnaround). Admin-created accounts default to "active".
   */
  status: 'active' | 'inactive' | 'pending';
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files".
 */
export interface File {
  id: number;
  /**
   * Set automatically on upload; used for update ownership.
   */
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cohorts".
 */
export interface Cohort {
  id: number;
  name: string;
  tracks: ('truck-driving' | 'mechanics' | 'ict' | 'supply-chain' | 'business-management')[];
  startDate: string;
  endDate: string;
  status: 'draft' | 'open' | 'active' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: number;
  intern: number | User;
  cohort: number | Cohort;
  /**
   * Assigned supervisor/"Mentor" for this intern — drives the §4/§6.6/§6.8 "assigned interns" access scoping.
   */
  supervisor?: (number | null) | User;
  track: 'truck-driving' | 'mechanics' | 'ict' | 'supply-chain' | 'business-management';
  outcome?: ('in-progress' | 'graduated' | 'resigned' | 'terminated') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invites".
 */
export interface Invite {
  id: number;
  cohort: number | Cohort;
  track: 'truck-driving' | 'mechanics' | 'ict' | 'supply-chain' | 'business-management';
  /**
   * Auto-generated. The invite link is https://<app>/register?token=<this>.
   */
  token?: string | null;
  /**
   * Auto-set to 24h after creation (§6.2).
   */
  expiresAt?: string | null;
  /**
   * Admin's discretion, e.g. if the link leaked (§6.2). A revoked invite is rejected the same as an expired one.
   */
  revoked?: boolean | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contracts".
 */
export interface Contract {
  id: number;
  trainer: number | User;
  cohort: number | Cohort;
  status: 'draft' | 'sent' | 'signed' | 'active' | 'released';
  /**
   * Signed, scanned contract upload.
   */
  file?: (number | null) | File;
  /**
   * Reference only — used to produce session-count evidence for the trainer's own invoice. Not processed for payment (§3, §6.4).
   */
  ratePerSession?: number | null;
  /**
   * Standing media-release consent from the Trainers Agreement (name/photo/video usable in promotional material).
   */
  mediaConsent?: boolean | null;
  /**
   * "A trainer can flag/request completion, but admin makes the final transition" (§6.4, confirmed). Setting this does not itself release the contract — admin still moves status to Released/Discharged.
   */
  releaseRequested?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules".
 */
export interface Module {
  id: number;
  track: 'truck-driving' | 'mechanics' | 'ict' | 'supply-chain' | 'business-management';
  name: string;
  curriculumReference?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-sessions".
 */
export interface TrainingSession {
  id: number;
  module: number | Module;
  trainer: number | User;
  cohort: number | Cohort;
  scheduledDate: string;
  status: 'scheduled' | 'completed' | 'rescheduled' | 'cancelled';
  reminderStatus?: ('pending' | 'sent') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "module-notes".
 */
export interface ModuleNote {
  id: number;
  session: number | TrainingSession;
  trainer: number | User;
  /**
   * Prose write-up of what was taught.
   */
  content?: string | null;
  slideDeck?: (number | null) | File;
  assignment?: (number | null) | File;
  /**
   * End-of-module assessment report (25 questions: 15 MCQ, 5 true/false, 1 case study worth 5 structured questions — §6.4).
   */
  assessmentReport?: (number | null) | File;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scores".
 */
export interface Score {
  id: number;
  intern: number | User;
  module: number | Module;
  value: number;
  notes?: string | null;
  /**
   * Controls whether the intern can see this score yet (§6.5).
   */
  finalized?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logbook-entries".
 */
export interface LogbookEntry {
  id: number;
  intern: number | User;
  cohort?: (number | null) | Cohort;
  type: 'driver' | 'non-driver';
  author: 'self' | 'supervisor';
  date: string;
  trip?: {
    area?: string | null;
    kmsDriven?: number | null;
    timeFrom?: string | null;
    timeTo?: string | null;
    activities?: ('dispatch' | 'offloading' | 'fueling' | 'checkpoint')[] | null;
    lessons?: string | null;
  };
  supervisorRollup?: {
    distanceDriven?: number | null;
    areaRegion?: string | null;
    areasOfImprovement?: string | null;
  };
  week?: {
    startDate?: string | null;
    endDate?: string | null;
    projectAssigned?: string | null;
    activitiesAndResources?: string | null;
    notes?: string | null;
  };
  supervisorComment?: string | null;
  status?: ('draft' | 'submitted' | 'reviewed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evaluations".
 */
export interface Evaluation {
  id: number;
  intern: number | User;
  /**
   * Supervisor for standard evaluations; trainer for driving-skills checkpoints (§6.5).
   */
  author: number | User;
  cohort: number | Cohort;
  type: 'standard' | 'driving-skills-baseline' | 'driving-skills-final';
  criteria?: string | null;
  outcome?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workplans".
 */
export interface Workplan {
  id: number;
  supervisor: number | User;
  intern: number | User;
  cohort: number | Cohort;
  content?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  intern: number | User;
  type: 'national-id' | 'driving-licence' | 'certificate-of-good-conduct' | 'sha' | 'kra-pin' | 'nssf' | 'other';
  file: number | File;
  verificationStatus: 'pending' | 'verified' | 'rejected';
  rejectionReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-assets".
 */
export interface MediaAsset {
  id: number;
  cohort: number | Cohort;
  visibilityScope: 'admin-only' | 'cohort-extended';
  /**
   * Whether the depicted intern/trainer has consented to promotional use (§6.4).
   */
  consentGiven?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alumni-profiles".
 */
export interface AlumniProfile {
  id: number;
  intern: number | User;
  /**
   * The public Talent Board display name (§6.9 public field) — separate from Users.name, since the intern's account isn't publicly readable.
   */
  name: string;
  photo?: (number | null) | Media;
  employmentStatus?: string | null;
  /**
   * Driving class certifications, defensive driving certification, diploma/course names and issuing institutions (§6.9).
   */
  courses?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  workExperience?:
    | {
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Narrative skills/ability summary: soft skills, technical skills gained, notable achievements (§6.9).
   */
  bio?: string | null;
  email?: string | null;
  phone?: string | null;
  /**
   * Opt-in step at graduation for appearing on the public Talent Board; self-service, can be withdrawn at any time (§6.9).
   */
  optedIn?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  content: string;
  author: number | User;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'sendSessionReminder';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'sendSessionReminder') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'files';
        value: number | File;
      } | null)
    | ({
        relationTo: 'cohorts';
        value: number | Cohort;
      } | null)
    | ({
        relationTo: 'enrollments';
        value: number | Enrollment;
      } | null)
    | ({
        relationTo: 'invites';
        value: number | Invite;
      } | null)
    | ({
        relationTo: 'contracts';
        value: number | Contract;
      } | null)
    | ({
        relationTo: 'modules';
        value: number | Module;
      } | null)
    | ({
        relationTo: 'training-sessions';
        value: number | TrainingSession;
      } | null)
    | ({
        relationTo: 'module-notes';
        value: number | ModuleNote;
      } | null)
    | ({
        relationTo: 'scores';
        value: number | Score;
      } | null)
    | ({
        relationTo: 'logbook-entries';
        value: number | LogbookEntry;
      } | null)
    | ({
        relationTo: 'evaluations';
        value: number | Evaluation;
      } | null)
    | ({
        relationTo: 'workplans';
        value: number | Workplan;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'media-assets';
        value: number | MediaAsset;
      } | null)
    | ({
        relationTo: 'alumni-profiles';
        value: number | AlumniProfile;
      } | null)
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  status?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "files_select".
 */
export interface FilesSelect<T extends boolean = true> {
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cohorts_select".
 */
export interface CohortsSelect<T extends boolean = true> {
  name?: T;
  tracks?: T;
  startDate?: T;
  endDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  intern?: T;
  cohort?: T;
  supervisor?: T;
  track?: T;
  outcome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invites_select".
 */
export interface InvitesSelect<T extends boolean = true> {
  cohort?: T;
  track?: T;
  token?: T;
  expiresAt?: T;
  revoked?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contracts_select".
 */
export interface ContractsSelect<T extends boolean = true> {
  trainer?: T;
  cohort?: T;
  status?: T;
  file?: T;
  ratePerSession?: T;
  mediaConsent?: T;
  releaseRequested?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules_select".
 */
export interface ModulesSelect<T extends boolean = true> {
  track?: T;
  name?: T;
  curriculumReference?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-sessions_select".
 */
export interface TrainingSessionsSelect<T extends boolean = true> {
  module?: T;
  trainer?: T;
  cohort?: T;
  scheduledDate?: T;
  status?: T;
  reminderStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "module-notes_select".
 */
export interface ModuleNotesSelect<T extends boolean = true> {
  session?: T;
  trainer?: T;
  content?: T;
  slideDeck?: T;
  assignment?: T;
  assessmentReport?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scores_select".
 */
export interface ScoresSelect<T extends boolean = true> {
  intern?: T;
  module?: T;
  value?: T;
  notes?: T;
  finalized?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logbook-entries_select".
 */
export interface LogbookEntriesSelect<T extends boolean = true> {
  intern?: T;
  cohort?: T;
  type?: T;
  author?: T;
  date?: T;
  trip?:
    | T
    | {
        area?: T;
        kmsDriven?: T;
        timeFrom?: T;
        timeTo?: T;
        activities?: T;
        lessons?: T;
      };
  supervisorRollup?:
    | T
    | {
        distanceDriven?: T;
        areaRegion?: T;
        areasOfImprovement?: T;
      };
  week?:
    | T
    | {
        startDate?: T;
        endDate?: T;
        projectAssigned?: T;
        activitiesAndResources?: T;
        notes?: T;
      };
  supervisorComment?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evaluations_select".
 */
export interface EvaluationsSelect<T extends boolean = true> {
  intern?: T;
  author?: T;
  cohort?: T;
  type?: T;
  criteria?: T;
  outcome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workplans_select".
 */
export interface WorkplansSelect<T extends boolean = true> {
  supervisor?: T;
  intern?: T;
  cohort?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  intern?: T;
  type?: T;
  file?: T;
  verificationStatus?: T;
  rejectionReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-assets_select".
 */
export interface MediaAssetsSelect<T extends boolean = true> {
  cohort?: T;
  visibilityScope?: T;
  consentGiven?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alumni-profiles_select".
 */
export interface AlumniProfilesSelect<T extends boolean = true> {
  intern?: T;
  name?: T;
  photo?: T;
  employmentStatus?: T;
  courses?:
    | T
    | {
        name?: T;
        id?: T;
      };
  workExperience?:
    | T
    | {
        description?: T;
        id?: T;
      };
  bio?: T;
  email?: T;
  phone?: T;
  optedIn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  author?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendSessionReminder".
 */
export interface TaskSendSessionReminder {
  input: {
    sessionId: number;
    scheduledDateAtQueueTime: string;
    reason: 'reminder' | 'rescheduled';
  };
  output: {
    recipientCount?: number | null;
    skippedReason?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}